### ISSUE TITLE
java.util.zip.ZipException: invalid code lengths set

### ISSUE THREAD

**Issue by billward** [nhnb/zipdiff#2]
Any time I use zipdiff I am getting this error. The zip files in question were made using the Linux 'zip' command and as far as I can tell there is no issue with the file contents.

java.util.zip.ZipException: invalid code lengths set
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:163)
        at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:109)
        at zipdiff.DifferenceCalculator.processEmbeddedZipFile(DifferenceCalculator.java:311)
        at zipdiff.DifferenceCalculator.processZipEntry(DifferenceCalculator.java:297)
        at zipdiff.DifferenceCalculator.processZipEntry(DifferenceCalculator.java:265)
        at zipdiff.DifferenceCalculator.processEmbeddedZipFile(DifferenceCalculator.java:310)
        at zipdiff.DifferenceCalculator.processZipEntry(DifferenceCalculator.java:297)
        at zipdiff.DifferenceCalculator.buildZipEntryMap(DifferenceCalculator.java:235)
        at zipdiff.DifferenceCalculator.calculateDifferences(DifferenceCalculator.java:374)
        at zipdiff.DifferenceCalculator.getDifferences(DifferenceCalculator.java:462)
        at zipdiff.Main.main(Main.java:218)

**Comment by nhnb** [comment]
The error occurs inside the Java core code. Which java version are you using? Could you attach a sample zip file with the issue?
